## Bootcamp | Project 5 | NumPy

In [1]:
import numpy as np
import pandas as pd
import array as arr
import matplotlib.pyplot as plt

In [2]:
number_matrix=np.arange(0,200,2).reshape(10,10)
print(number_matrix)

[[  0   2   4   6   8  10  12  14  16  18]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 60  62  64  66  68  70  72  74  76  78]
 [ 80  82  84  86  88  90  92  94  96  98]
 [100 102 104 106 108 110 112 114 116 118]
 [120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 192 194 196 198]]


In [15]:
numbers=input('Please enter two numbers:')
chosen_numbers=list(numbers)
columns=chosen_numbers[0]
rows=chosen_numbers[1]
num_matrix_ones= np.ones((int(columns),int(rows)))
num_matrix_zeros=np.zeros((int(columns)-2,int(rows)-2))

print(num_mat_ones) 
print(num_mat_zeros)


Please enter two numbers:68
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
numbers=input('Please enter two numbers:')
chosen_numbers=list(numbers)
columns=int(chosen_numbers[0])
rows=int(chosen_numbers[1])
num_matrix= np.ones((columns,rows))
c=columns-1
r=rows-1
num_matrix[1:c,1:r]=[0]
print(num_matrix)

Please enter two numbers:68
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
